import QtQuick
import QtQuick.Layouts
import QtQuick.Dialogs
import QtCore

import Logos.Theme
import Logos.Controls

import "../controls"
import "infoContent.js" as InfoContent
import "OnboardingPaths.js" as OnboardingPaths

// Node settings, one card per concern.
ColumnLayout {
    id: root

    // --- Public API ---
    property string userConfig: ""
    property string deploymentConfig: ""
    property bool useGeneratedConfig: false
    // The chooser is not reachable while the node is up: changing config under
    // a running node would leave the two disagreeing.
    property bool canChange: true
    // Offer the rebuild only when the node has actually refused this config.
    // There is no way to validate one without starting the node, so the rest of
    // the time this cannot honestly be recommended.
    property bool configStale: false

    // Whether the node is currently claiming mined rewards on its own. A
    // RUNTIME flag, not a stored setting — see the card below.
    property bool autoClaimRunning: false
    property bool nodeRunning: false

    // A config was repointed and the node has not been started since. Changing
    // a path takes effect immediately but does nothing visible until the node
    // runs, so without this the user acts and is told nothing.
    property bool configChangedSinceStart: false
    // Where the node keeps db/, state/ and logs/. Empty when no config is set
    // or the node has not run yet.
    property string nodeDataDir: ""
    // The keystore, or empty when there is none for this config yet.
    property string nodeKeystorePath: ""
    property bool keysBackedUp: false
    // Why the last backup failed, or empty. Successes are announced by the
    // host as a toast rather than kept here.
    property string backupError: ""

    signal backupKeystoreRequested(string destinationPath)
    signal userConfigSelected(string path)
    signal deploymentConfigSelected(string path)

    spacing: Theme.spacing.large

    signal updateConfigRequested()
    signal startNewNodeRequested()
    signal autoClaimToggled(bool enabled)


    LogosFrame {
        Layout.fillWidth: true
        padding: Theme.spacing.large
        backgroundColor: Theme.palette.surfaceRaised
        borderColor: "transparent"
        radius: Theme.spacing.radiusLarge

        contentItem: ColumnLayout {
            spacing: Theme.spacing.small

            RowLayout {
                Layout.fillWidth: true
                Layout.fillHeight: false
                Layout.bottomMargin: Theme.spacing.small
                spacing: Theme.spacing.small

                LogosText {
                    text: qsTr("Node")
                    color: Theme.palette.text
                    font.pixelSize: Theme.typography.panelTitleText
                    font.weight: Theme.typography.weightMedium
                }

                Item { Layout.fillWidth: true }

                LogosInfoButton {
                    Layout.alignment: Qt.AlignVCenter
                    title: qsTr("Node config")
                    dialogContentItem: InfoSections { info: InfoContent.nodeConfig }
                }
            }

            RowLayout {
                Layout.fillWidth: true
                spacing: Theme.spacing.small

                LogosText {
                    text: qsTr("User Config")
                    color: Theme.palette.text
                    font.pixelSize: Theme.typography.secondaryText
                    font.weight: Theme.typography.weightMedium
                }

                Item { Layout.fillWidth: true }

                // Copies the full path, not the elided display string.
                LogosCopyButton {
                    visible: root.userConfig.length > 0
                    value: root.userConfig
                }
            }

            RowLayout {
                Layout.fillWidth: true
                spacing: Theme.spacing.small

                LogosTextField {
                    id: userConfigField
                    objectName: "settingsUserConfigField"
                    Layout.fillWidth: true
                    enabled: root.canChange
                    placeholderText: qsTr("No file selected")
                    text: root.userConfig
                }

                Connections {
                    target: userConfigField.textInput
                    function onEditingFinished() {
                        root.userConfigSelected(userConfigField.text.trim())
                    }
                }

                LogosButton {
                    objectName: "settingsBrowseUserConfigButton"
                    enabled: root.canChange
                    text: qsTr("Browse")
                    onClicked: userConfigFileDialog.open()
                }
            }

            LogosText {
                Layout.fillWidth: true
                visible: root.useGeneratedConfig
                text: qsTr("Generated by this app.")
                color: Theme.palette.textTertiary
                font.pixelSize: Theme.typography.secondaryText
            }

            RowLayout {
                Layout.topMargin: Theme.spacing.small
                Layout.fillWidth: true
                spacing: Theme.spacing.small

                LogosText {
                    text: qsTr("Deployment Config")
                    color: Theme.palette.text
                    font.pixelSize: Theme.typography.secondaryText
                    font.weight: Theme.typography.weightMedium
                }

                Item { Layout.fillWidth: true }

                LogosCopyButton {
                    visible: root.deploymentConfig.length > 0
                    value: root.deploymentConfig
                }
            }

            RowLayout {
                Layout.fillWidth: true
                spacing: Theme.spacing.small

                LogosTextField {
                    id: deploymentField
                    objectName: "settingsDeploymentConfigField"
                    Layout.fillWidth: true
                    enabled: root.canChange
                    placeholderText: qsTr("Built-in default")
                    text: root.deploymentConfig
                }

                Connections {
                    target: deploymentField.textInput
                    function onEditingFinished() {
                        root.deploymentConfigSelected(deploymentField.text.trim())
                    }
                }

                LogosButton {
                    objectName: "settingsBrowseDeploymentButton"
                    enabled: root.canChange
                    text: qsTr("Browse")
                    onClicked: deploymentConfigFileDialog.open()
                }
            }

            // The fallback is silent otherwise, and it is not harmless: an
            // uninscribed built-in deployment is what produces a genesis far in
            // the future and a chain id the node cannot report.
            LogosText {
                Layout.fillWidth: true
                visible: root.deploymentConfig.length === 0
                wrapMode: Text.WordWrap
                text: qsTr("Using the deployment built into this build.")
                color: Theme.palette.textTertiary
                font.pixelSize: Theme.typography.secondaryText
            }

            LogosNotice {
                objectName: "configChangedNotice"
                Layout.fillWidth: true
                Layout.topMargin: Theme.spacing.small
                shown: root.configChangedSinceStart && !root.nodeRunning
                severity: LogosNotice.Info
                message: qsTr("Config changed. Start the node to use it.")
            }

            RowLayout {
                Layout.topMargin: Theme.spacing.medium
                Layout.alignment: Qt.AlignRight
                spacing: Theme.spacing.small

                LogosButton {
                    objectName: "updateConfigButton"
                    visible: root.configStale
                    enabled: root.canChange
                    variant: LogosButton.Variant.Primary
                    text: qsTr("Update config")
                    onClicked: root.updateConfigRequested()
                }
                LogosButton {
                    objectName: "startNewNodeButton"
                    enabled: root.canChange
                    text: qsTr("Start a new node")
                    onClicked: root.startNewNodeRequested()
                }
            }
        }
    }

    // ---- Back up your keys ----
    LogosFrame {
        Layout.fillWidth: true
        padding: Theme.spacing.large
        backgroundColor: Theme.palette.surfaceRaised
        borderColor: "transparent"
        radius: Theme.spacing.radiusLarge

        contentItem: ColumnLayout {
            spacing: Theme.spacing.small

            RowLayout {
                Layout.fillWidth: true
                Layout.bottomMargin: Theme.spacing.small
                spacing: Theme.spacing.small

                LogosText {
                    text: qsTr("Back up your keys")
                    color: Theme.palette.text
                    font.pixelSize: Theme.typography.panelTitleText
                    font.weight: Theme.typography.weightMedium
                }

                LogosBadge {
                    objectName: "keysBackedUpBadge"
                    visible: root.keysBackedUp
                    text: qsTr("Done")
                    color: Theme.palette.success
                }

                Item { Layout.fillWidth: true }
            }

            LogosText {
                Layout.fillWidth: true
                wrapMode: Text.WordWrap
                text: qsTr("Your keystore holds the keys to your accounts. It is the one file "
                           + "nothing else can replace — lose it and the rewards those accounts "
                           + "hold are gone with it. Save a copy somewhere safe, away from this "
                           + "machine, and you can recover the accounts even if everything here "
                           + "is lost.")
                color: Theme.palette.textSecondary
                font.pixelSize: Theme.typography.secondaryText
            }

            HashRow {
                Layout.fillHeight: false
                visible: root.nodeKeystorePath.length > 0
                label: qsTr("Keystore")
                labelWidth: 72
                value: root.nodeKeystorePath
            }

            LogosText {
                Layout.fillWidth: true
                wrapMode: Text.WordWrap
                visible: root.nodeKeystorePath.length === 0
                text: qsTr("No keystore found yet — it appears once a config is set and the "
                           + "node has run at least once.")
                color: Theme.palette.textTertiary
                font.pixelSize: Theme.typography.secondaryText
            }

            LogosButton {
                objectName: "backupKeystoreButton"
                Layout.topMargin: Theme.spacing.small
                Layout.alignment: Qt.AlignRight
                variant: LogosButton.Variant.Primary
                enabled: root.nodeKeystorePath.length > 0
                text: qsTr("Download keystore.yaml")
                onClicked: keystoreSaveDialog.open()
            }

            LogosNotice {
                Layout.fillWidth: true
                objectName: "backupResultNotice"
                shown: root.backupError.length > 0
                severity: LogosNotice.Error
                title: qsTr("Backup failed")
                message: root.backupError
                closable: true
                onDismissed: root.backupError = ""
                actions: [
                    LogosCopyButton { value: root.backupError }
                ]
            }
        }
    }

    // ---- Mining ----
    LogosFrame {
        Layout.fillWidth: true
        padding: Theme.spacing.large
        backgroundColor: Theme.palette.surfaceRaised
        borderColor: "transparent"
        radius: Theme.spacing.radiusLarge

        contentItem: ColumnLayout {
            spacing: Theme.spacing.small

            RowLayout {
                Layout.fillWidth: true
                Layout.fillHeight: false
                Layout.bottomMargin: Theme.spacing.small
                spacing: Theme.spacing.small

                LogosText {
                    text: qsTr("Mining")
                    color: Theme.palette.text
                    font.pixelSize: Theme.typography.panelTitleText
                    font.weight: Theme.typography.weightMedium
                }

                Item { Layout.fillWidth: true }

                LogosInfoButton {
                    Layout.alignment: Qt.AlignVCenter
                    title: qsTr("Auto-claim")
                    dialogContentItem: InfoSections { info: InfoContent.autoClaim }
                }
            }

            RowLayout {
                Layout.fillWidth: true
                Layout.fillHeight: false
                spacing: Theme.spacing.small

                LogosText {
                    text: qsTr("Auto-claim")
                    font.pixelSize: Theme.typography.primaryText
                }
                LogosBadge {
                    objectName: "autoClaimRecommendedBadge"
                    text: qsTr("Recommended")
                    color: Theme.palette.success
                }

                Item { Layout.fillWidth: true }

                LogosSwitch {
                    objectName: "autoClaimSwitch"
                    checked: root.autoClaimRunning
                    enabled: root.nodeRunning
                    onToggled: root.autoClaimToggled(checked)
                }
            }

            LogosText {
                Layout.fillWidth: true
                Layout.topMargin: Theme.spacing.small
                wrapMode: Text.WordWrap
                text: qsTr("The rest of mining — how many threads the search uses, which "
                           + "accounts auto-claim pays and the balance it stops at — lives in "
                           + "the config file, under pow. Copy its path from the Node card "
                           + "then restart the node.")
                color: Theme.palette.textTertiary
                font.pixelSize: Theme.typography.secondaryText
            }
        }
    }

    // ---- Destructive ----
    // A path and instructions, not a button.
    LogosFrame {
        Layout.fillWidth: true
        padding: Theme.spacing.large
        backgroundColor: Theme.palette.surfaceRaised
        borderColor: Theme.palette.error
        radius: Theme.spacing.radiusLarge

        contentItem: ColumnLayout {
            spacing: Theme.spacing.small

            LogosText {
                Layout.bottomMargin: Theme.spacing.small
                text: qsTr("Reset the database")
                color: Theme.palette.text
                font.pixelSize: Theme.typography.panelTitleText
                font.weight: Theme.typography.weightMedium
            }

            LogosText {
                Layout.fillWidth: true
                wrapMode: Text.WordWrap
                text: qsTr("If the node is stuck or will not start, its database may be at "
                           + "fault. Stop the node, delete the folder below, then start it "
                           + "again — it will re-sync the chain from its peers. Your keys and "
                           + "config files are untouched.")
                color: Theme.palette.textSecondary
                font.pixelSize: Theme.typography.secondaryText
            }

            HashRow {
                Layout.fillHeight: false
                visible: root.nodeDataDir.length > 0
                label: qsTr("Database")
                labelWidth: 72
                value: root.nodeDataDir
            }

            LogosText {
                Layout.fillWidth: true
                wrapMode: Text.WordWrap
                visible: root.nodeDataDir.length === 0
                text: qsTr("No database found yet — it appears once a config is set and the "
                           + "node has run at least once.")
                color: Theme.palette.textTertiary
                font.pixelSize: Theme.typography.secondaryText
            }
        }
    }


    FileDialog {
        id: keystoreSaveDialog
        title: qsTr("Save a copy of your keystore")
        modality: Qt.NonModal
        fileMode: FileDialog.SaveFile
        currentFolder: StandardPaths.standardLocations(StandardPaths.DocumentsLocation)[0]
        defaultSuffix: "yaml"
        nameFilters: [qsTr("Keystore files (*.yaml *.yml)"), qsTr("All files (*)")]
        onAccepted: root.backupKeystoreRequested(selectedFile)
    }


    FileDialog {
        id: userConfigFileDialog
        modality: Qt.NonModal
        title: qsTr("Select your user config")
        nameFilters: [qsTr("YAML files (*.yaml *.yml)"), qsTr("All files (*)")]
        currentFolder: OnboardingPaths.toFolderUrl(root.userConfig)
                       || StandardPaths.standardLocations(StandardPaths.DocumentsLocation)[0]
        onAccepted: root.userConfigSelected(OnboardingPaths.toLocalPath(selectedFile))
    }

    FileDialog {
        id: deploymentConfigFileDialog
        modality: Qt.NonModal
        title: qsTr("Select your deployment config")
        nameFilters: [qsTr("YAML files (*.yaml *.yml)"), qsTr("All files (*)")]
        currentFolder: OnboardingPaths.toFolderUrl(root.deploymentConfig)
                       || StandardPaths.standardLocations(StandardPaths.DocumentsLocation)[0]
        onAccepted: root.deploymentConfigSelected(OnboardingPaths.toLocalPath(selectedFile))
    }
}
